"""Parity test: bandnorm_rust must match BandNorm's R reference.

Reference data is generated by `reference_scgad.R` and committed under
`tests/data/`. The R script computes raw counts, depth-normalised counts,
and final Z-scored GAD scores from the official BandNorm-shipped
`scGADExample.rda` (1290919 contact pairs × 100 cells) using the full
`mm9Annotations` (10180 genes).

We assert:
  - raw counts: integer-exact (max abs diff = 0) on every kept gene
  - GAD scores: < 1e-10 max abs diff (covers all post-processing steps)
"""
from __future__ import annotations

import subprocess
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

DATA_DIR = Path(__file__).parent / "data"
EXAMPLE_RDA = "/scratch/users/steorra/analysis/omicverse_dev/BandNorm/data/scGADExample.rda"
ANNOTATIONS_RDA = "/scratch/users/steorra/analysis/omicverse_dev/BandNorm/data/Annotations.rda"
RSCRIPT = "/scratch/users/steorra/env/CMAP/bin/Rscript"


def _ensure_reference():
    """Generate R reference if not already on disk."""
    needed = [DATA_DIR / f for f in
              ("scgad_raw.tsv", "scgad_depth_norm.tsv", "scgad_gad.tsv")]
    if all(p.exists() for p in needed):
        return
    DATA_DIR.mkdir(exist_ok=True)
    subprocess.run([RSCRIPT,
                    str(Path(__file__).parent / "reference_scgad.R"),
                    EXAMPLE_RDA, ANNOTATIONS_RDA, str(DATA_DIR / "scgad")],
                   check=True)


def _load_inputs():
    """Load scgad_df + mm9Annotations from the BandNorm .rda files via
    a one-shot Rscript that re-emits them as TSV."""
    pairs_tsv = DATA_DIR / "scgad_input_pairs.tsv"
    genes_tsv = DATA_DIR / "scgad_input_genes.tsv"
    if not pairs_tsv.exists() or not genes_tsv.exists():
        DATA_DIR.mkdir(exist_ok=True)
        rscript = (
            f'load("{EXAMPLE_RDA}"); '
            f'load("{ANNOTATIONS_RDA}"); '
            'library(data.table); '
            f'fwrite(setDT(scgad_df), "{pairs_tsv}", sep="\\t"); '
            f'fwrite(setDT(mm9Annotations), "{genes_tsv}", sep="\\t")'
        )
        subprocess.run([RSCRIPT, "-e", rscript], check=True)
    pairs = pd.read_csv(pairs_tsv, sep="\t")
    genes = pd.read_csv(genes_tsv, sep="\t")
    return pairs, genes


@pytest.fixture(scope="module")
def reference():
    _ensure_reference()
    raw = pd.read_csv(DATA_DIR / "scgad_raw.tsv", sep="\t").set_index("gene")
    depth = pd.read_csv(DATA_DIR / "scgad_depth_norm.tsv", sep="\t").set_index("gene")
    gad = pd.read_csv(DATA_DIR / "scgad_gad.tsv", sep="\t").set_index("gene")
    return {"raw": raw, "depth": depth, "gad": gad}


@pytest.fixture(scope="module")
def inputs():
    return _load_inputs()


def test_raw_counts_exact(inputs, reference):
    """Rust raw aggregation must be integer-exact vs R."""
    bn = pytest.importorskip("bandnorm_rust")
    if not bn._RUST_AVAILABLE:
        pytest.skip("Rust extension not built")

    pairs, genes = inputs
    raw_rust = bn.scgad(pairs, genes, resolution=10_000, depth_norm=False)

    raw_r = reference["raw"]
    # R drops nothing in raw output. Rust also keeps full gene set (no filter
    # without depth_norm). Sort both by gene name and cell name for exact compare.
    common_cells = sorted(set(raw_r.columns) & set(raw_rust.columns))
    common_genes = sorted(set(raw_r.index) & set(raw_rust.index))
    assert len(common_cells) == 100, f"got {len(common_cells)} cells in common"
    assert len(common_genes) == len(raw_r.index) == 10180

    a = raw_r.loc[common_genes, common_cells].to_numpy()
    b = raw_rust.loc[common_genes, common_cells].to_numpy()
    diff = np.abs(a - b)
    max_diff = diff.max()
    n_diff = (diff > 0).sum()
    print(f"\n  raw counts: max abs diff = {max_diff}, "
          f"non-zero diffs = {n_diff} / {a.size}")
    assert max_diff == 0, f"raw counts diverge from R: max diff {max_diff}"


def test_gad_scores_close(inputs, reference):
    """Z-scored GAD: max abs diff < 1e-10 vs R."""
    bn = pytest.importorskip("bandnorm_rust")
    if not bn._RUST_AVAILABLE:
        pytest.skip("Rust extension not built")

    pairs, genes = inputs
    gad_rust = bn.scgad(pairs, genes, resolution=10_000, depth_norm=True)
    gad_r = reference["gad"]

    common_cells = sorted(set(gad_r.columns) & set(gad_rust.columns))
    common_genes = sorted(set(gad_r.index) & set(gad_rust.index))
    print(f"\n  shapes: R = {gad_r.shape}, rust = {gad_rust.shape}, "
          f"common = ({len(common_genes)}, {len(common_cells)})")

    a = gad_r.loc[common_genes, common_cells].to_numpy()
    b = gad_rust.loc[common_genes, common_cells].to_numpy()
    diff = np.abs(a - b)
    max_diff = float(np.nanmax(diff))
    pearson_r = float(np.corrcoef(a.ravel(), b.ravel())[0, 1])
    print(f"  GAD: max abs diff = {max_diff:.3e}, pearson r = {pearson_r:.10f}")
    assert max_diff < 1e-10, f"GAD diverges by {max_diff}"
